baseURL = "https://hvariant.github.io"
languageCode = "en-us"
title = "Zhansong Li's Personal Website"
theme = "minimal"

[params]
    author = "Zhansong Li"
    description = ""
    githubUsername = "hvariant"
    backgroundColor = "white"
    font = "Open Sans"
    highlight = true

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/notes"
    name = "Notes"
    weight = 1

[[menu.icon]]
    url = "mailto:lizhansong@hvariant.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/hvariant/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://linkedin.com/in/zhansongli"
    name = "linkedin"
    weight = 3
